# Generated by Django 3.0.7 on 2020-07-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=40)),
                ('company_name', models.CharField(max_length=80)),
                ('job_description', models.TextField(blank=True, default='N/A', null=True)),
                ('experience', models.IntegerField()),
                ('address', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
                ('state', models.CharField(max_length=20)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default='N/A')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_apis.Category')),
            ],
        ),
    ]
