# Generated by Django 3.0.7 on 2020-08-08 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_apis', '0003_job_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, default='N/A', null=True),
        ),
    ]
